name: rtmp_publisher_example
description: Demonstrates how to use the rtmp_publisher plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  rtmp_publisher:
    path: ../

  path_provider: ^2.0.0
  cupertino_icons: ^1.0.0
  video_player: ^2.0.0
  wakelock: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
